version: '3'
services:
  api-notes:
    image: node:18-alpine
    container_name: api-notes
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=production
    command: npm start
    ports:
      - 4000:4000